Repository ICCAS2024-Helper/facialFit-frontend, pull requests merged in 2024-07, with the labels that each got.

#6 fix: shop api 수정
  lib/shop/shop_main.dart
Labels: bug

#8 Game check
  lib/game/camera_view.dart
  lib/game/controller/scan_controller.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#9 New d2
  assets/clear.mp3
  assets/fail.MP3
  assets/images/Congratulation!.png
  assets/images/Game Over.png
  assets/images/birth.png
  assets/images/clapping.png
  assets/images/sad.png
  lib/TestFiles/login.dart
  lib/TestFiles/register.dart
  lib/TestFiles/register2.dart
  lib/TestFiles/register_API.dart
  lib/TestFiles/shop_test1.dart
  lib/etc/buttons/calendar.dart
  lib/etc/buttons/capture/button.dart
  lib/etc/buttons/capture/testmlkit.dart
  lib/etc/buttons/capture/topimage.dart
  lib/etc/buttons/home.dart
  lib/etc/buttons/pop.dart
  lib/etc/buttons/quest.dart
  lib/etc/buttons/setting.dart
  lib/etc/buttons/statistics.dart
  lib/etc/buttons/stop.dart
  lib/etc/buttons/test.dart
  lib/etc/buttons/white/calendar.dart
  lib/etc/buttons/white/quest.dart
  lib/etc/buttons/white/setting.dart
  lib/etc/calendar.dart
  lib/etc/calendar_picker.dart
  lib/etc/coin.dart
  lib/etc/loading.dart
  lib/etc/progressbar/progressbar.dart
  lib/etc/progressbar/progressbar_controller.dart
  lib/etc/quest.dart
  lib/etc/quest_list.dart
  lib/etc/statistics.dart
  lib/etc/stop.dart
  lib/game/bonus/play.dart
  lib/game/bonus/start.dart
  lib/game/camera_screen.dart
  lib/game/camera_view.dart
  lib/game/ending/fail.dart
  lib/game/ending/success.dart
  lib/game/result/stageclear1.dart
  lib/game/result/stagefail1.dart
  lib/game/select.dart
  lib/game/timer.dart
  lib/main.dart
  lib/main/select.dart
  lib/main/stage.dart
  lib/main/statefullStage.dart
  lib/massage/play.dart
  lib/massage/select.dart
  lib/quest/quest_test1.dart
  lib/settings/mypage.dart
  lib/settings/select.dart
  pubspec.yaml
Labels: enhancement

#10 fix: audio 중복 수정
  lib/Service/AudioService.dart
  lib/game/controller/scan_controller.dart
  lib/main/main_stage.dart
Labels: bug

#13 fix: 오류 수정
  lib/game/controller/scan_controller.dart
  lib/main/main_stage.dart
Labels: bug

#15 Calendar
  assets/images/011-unicorn.png
  assets/images/018-unicorn.png
  assets/images/037-cat.png
  lib/calendar/calendar.dart
  lib/calendar/events_provider.dart
  lib/calendar/text_field.dart
  lib/calendar/user_info_provider.dart
  lib/main.dart
  lib/main/main_stage.dart
  linux/flutter/ephemeral/.plugin_symlinks/audioplayers_linux
  linux/flutter/ephemeral/.plugin_symlinks/file_selector_linux
  linux/flutter/ephemeral/.plugin_symlinks/image_picker_linux
  linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
  linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux
  linux/flutter/ephemeral/.plugin_symlinks/tflite_flutter
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#18 Feature select camera
  assets/gifs/sad1.gif
  assets/gifs/smile1.gif
  lib/game/bonus/play.dart
  lib/game/camera_screen.dart
  lib/game/camera_view.dart
  lib/game/controller/scan_controller.dart
  lib/game/mlkit/gallery_view.dart
  lib/game/showStatusImage.dart
  lib/main/main_stage.dart
  linux/flutter/ephemeral/.plugin_symlinks/audioplayers_linux
  linux/flutter/ephemeral/.plugin_symlinks/file_selector_linux
  linux/flutter/ephemeral/.plugin_symlinks/image_picker_linux
  linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
  linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux
  linux/flutter/ephemeral/.plugin_symlinks/tflite_flutter
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugin_registrant.h
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: feature

#19 fix: 스토리보너스 플레이, 폴더 정리 및 수정
  lib/game/bonus/bounsplay.dart
  lib/game/bonus/start.dart
  lib/game/controller/scan_controller.dart
  lib/game/story/start.dart
  lib/game/story/storyplay.dart
  lib/main/main_stage.dart
  pubspec.yaml
Labels: enhancement

#21 Fix: 충돌수정
  lib/main/main_stage.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugin_registrant.h
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
Labels: bug

#23 fix
  lib/main/main_stage.dart
Labels: bug

#24 New d6
  assets/images/android.jpg
  lib/game/bonus/bounsplay.dart
  lib/main.dart
  lib/main/setting.dart
  lib/story/story1.dart
  lib/story/story2.dart
  lib/story/story3.dart
  lib/story/story4.dart
  lib/story/story5.dart
  lib/survey.dart
Labels: feature

#25 fix bonus_game.dart UI수정
  lib/game/bonus/bonus_game.dart
  lib/game/bonus/bounsplay.dart
  lib/game/bonus/start.dart
  lib/main/main_stage.dart
Labels: bug, enhancement

#28 Fix
  lib/game/camera_view.dart
  lib/game/controller/scan_controller.dart
Labels: bug

#32 statistics추가
  lib/Service/AuthService.dart
  lib/main/mypage.dart
  lib/main/setting.dart
  lib/main/statistics.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#35 Fix main function
  assets/images/Logo.png
  assets/images/Parchment2.png
  assets/images/Quest2.png
  assets/images/Smile-Helper.png
  assets/images/calendar.png
  assets/images/coin.png
  assets/images/main_character.jpeg
  assets/images/main_character.png
  assets/images/setting2.png
  assets/images/speech_bubble.png
  assets/images/test.png
  ios/Runner/GeneratedPluginRegistrant.m
  lib/calendar/calendar.dart
  lib/css/screen.dart
  lib/css/screen_home.dart
  lib/game/story/start.dart
  lib/game/story/storyplay.dart
  lib/init.dart
  lib/login_main.dart
  lib/main.dart
  lib/main/main_stage.dart
  lib/main/mypage.dart
  lib/main/setting.dart
  lib/quest/quest_test2.dart
  lib/register_main.dart
  lib/shop/shop_main.dart
  lib/survey.dart
  linux/flutter/ephemeral/.plugin_symlinks/audioplayers_linux
  linux/flutter/ephemeral/.plugin_symlinks/file_selector_linux
  linux/flutter/ephemeral/.plugin_symlinks/image_picker_linux
  linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
  linux/flutter/ephemeral/.plugin_symlinks/shared_preferences_linux
  linux/flutter/ephemeral/.plugin_symlinks/tflite_flutter
  pubspec.lock
  pubspec.yaml
Labels: bug

#36 작동되게 수정
  lib/main/mypage.dart
  lib/main/setting.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: bug

#38 fix
  lib/main.dart
Labels: enhancement

#39 수정
  lib/calendar/calendar.dart
  lib/game/mlkit/file_utils.dart
  lib/main/main_stage.dart
  lib/main/statistics.dart
Labels: bug

#40 New d11
  lib/game/bonus/bonus_game.dart
  lib/game/result/stageclear1.dart
  lib/game/story/start.dart
  lib/game/story/storyplay.dart
  lib/main.dart
  lib/main/mypage.dart
  lib/quest/quest_test2.dart
Labels: enhancement

#41 ui 조금 수정
  lib/main/setting.dart
  lib/main/statistics.dart
  lib/register_main.dart
Labels: bug

#42 ui 조금 수정
  lib/main/main_stage.dart
  lib/main/mypage.dart
  lib/main/setting.dart
  lib/main/statistics.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#43 Fix
  assets/images/Calender.png
  assets/images/Parchment.png
  assets/images/Quest.png
  assets/images/Topic.png
  assets/images/light.png
  assets/images/main.png
  assets/images/main5.png
  assets/images/main_character.jpeg
  assets/images/refrigerator.png
  assets/images/setting.png
  lib/game/camera_view.dart
  lib/game/controller/camera_manager.dart
  lib/game/controller/face_recognition.dart
  lib/game/controller/scan_controller.dart
  lib/game/controller/scan_service/post_result.dart
  lib/game/controller/stage_manager.dart
  lib/game/controller/utils2.dart
  lib/game/countdown.dart
  lib/game/express_view.dart
  lib/game/mlkit/message_view.dart
  lib/game/showStatusImage.dart
  pubspec.yaml
Labels: bug

#46 fix
  lib/game/camera_screen.dart
  lib/game/camera_view.dart
  lib/game/controller/face_recognition.dart
  lib/game/controller/scan_controller.dart
  lib/game/controller/stage_manager.dart
  lib/game/countdown.dart
  lib/game/express_view.dart
  lib/game/mlkit/detector_view.dart
  lib/game/mlkit/message_view.dart
  lib/game/showStatusImage.dart
  lib/game/story/start.dart
  lib/game/story/storyplay.dart
  lib/global_binding.dart
  lib/main.dart
  lib/main/setting.dart
  lib/main/statistics.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#47 스테이지, 게임 count, 통계 API연동
  assets/wedding.mp4
  lib/game/result/stageclear1.dart
  lib/game/result/stageclear2.dart
  lib/game/result/stageclear3.dart
  lib/game/result/stageclear4.dart
  lib/game/result/stageclear5.dart
  lib/game/result/stageclear6.dart
  lib/game/story/finish.dart
  lib/game/story/story_stage.dart
  lib/hardmode/hard_mode_controller.dart
  lib/hardmode/hard_mode_controller2.dart
  lib/hardmode/hard_mode_controller3.dart
  lib/hardmode/hard_mode_controller4.dart
  lib/hardmode/hard_mode_controller5.dart
  lib/hardmode/hard_mode_controller6.dart
  lib/main.dart
  pubspec.yaml
Labels: enhancement

#48 Fix
  assets/images/stamp.png
  lib/calendar/calendar.dart
  lib/calendar/events_provider.dart
  lib/game/camera_screen.dart
  lib/game/camera_view.dart
  lib/game/controller/coordinates_translator.dart
  lib/game/controller/face_recognition.dart
  lib/game/controller/getPredict.dart
  lib/game/controller/mlkit.dart
  lib/game/controller/scan_controller.dart
  lib/game/controller/stage_manager.dart
  lib/game/countdown.dart
  lib/game/express_view.dart
  lib/game/mlkit/detector_view.dart
  lib/game/mlkit/face_detector_paint.dart
  lib/game/mlkit/face_painter.dart
  lib/game/mlkit/gallery_view.dart
  lib/game/mlkit/message_view.dart
  lib/game/mlkit/utils.dart
  lib/game/showStatusImage.dart
  lib/game/story/start.dart
  lib/game/story/story_stage.dart
  lib/game/story/storyplay.dart
  lib/global_binding.dart
  lib/hardmode/hard_mode_controller.dart
  lib/hardmode/hard_mode_controller2.dart
  lib/hardmode/hard_mode_controller3.dart
  lib/hardmode/hard_mode_controller4.dart
  lib/hardmode/hard_mode_controller5.dart
  lib/hardmode/hard_mode_controller6.dart
  lib/hardmode/hard_mode_screen.dart
  lib/init.dart
  lib/main.dart
  lib/main/main_stage.dart
  lib/main/mypage.dart
  lib/main/second_page.dart
  lib/main/setting.dart
  lib/quest/quest_test2.dart
  lib/shop/shop_main.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#49 배치만 수정
  lib/survey.dart
Labels: bug, enhancement

#50 Feature button change
  assets/images/countdown1.png
  assets/images/countdown2.png
  assets/images/countdown3.png
  assets/images/countdown4.png
  assets/images/countdown5.png
  lib/game/bonus/bonus_game.dart
  lib/game/story/prolog.dart
  lib/game/story/story_stage.dart
  lib/hardmode/hard_mode_controller.dart
  lib/hardmode/hard_mode_controller2.dart
  lib/hardmode/hard_mode_controller3.dart
  lib/hardmode/hard_mode_controller4.dart
  lib/hardmode/hard_mode_controller5.dart
  lib/hardmode/hard_mode_controller6.dart
  lib/hardmode/hard_mode_screen.dart
  lib/main/main_stage.dart
  lib/main/statistics.dart
  pubspec.yaml
Labels: enhancement

#51 fix
  lib/hardmode/hard_mode_controller.dart
  lib/hardmode/hard_mode_controller2.dart
  lib/hardmode/hard_mode_controller3.dart
  lib/hardmode/hard_mode_controller4.dart
  lib/hardmode/hard_mode_controller5.dart
  lib/hardmode/hard_mode_controller6.dart
  lib/hardmode/hard_mode_screen.dart
  lib/main/main_stage.dart
Labels: bug

#52 main fix 2
  lib/hardmode/hard_mode_screen.dart
Labels: bug
